default: &default
  host: localhost
  username: root
  password: tunecore
  encoding: utf8
  adapter: mysql2
  port: 3306

development:
  <<: *default
  database: readysetgo_development
  pool: 50

test:
  <<: *default
  database: readysetgo_test
